import type { Metadata } from "next";
import "./globals.css";
import { kanit } from "./ui/fonts";
import NavBar from "./ui/global/NavBar";

export const metadata: Metadata = {
  title: "learning next Js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} antialiased`}>{children}</body>
    </html>
  );
}
